(macro_definition "{" @range.extended _+ @range "}" @range.extended)
(block "{" @range.extended _+ @range "}" @range.extended)
(field_declaration_list "{" @range.extended _+ @range "}" @range.extended)
(enum_variant_list "{" @range.extended _+ @range "}" @range.extended)
(declaration_list "{" @range.extended _+ @range "}" @range.extended)
