(macro_definition . "{" . (_)+ @range . "}" . )
(block . "{" . (_)+ @range . "}" . )
(field_declaration_list . "{" . (_)+ @range . ","? . "}" . )
(enum_variant_list . "{" . (_)+ @range . ","? . "}" . )
(declaration_list . "{" . (_)+ @range . ","? . "}" . )
