(comment) @range

([
    (left_assignment)
    (left_assignment2)
    (equals_assignment)
    (super_assignment)
    (super_right_assignment)
    (right_assignment)
    (call)
    (function_definition)
    (lambda_function)
    (while)
    (if)
    (for)
    (repeat)
    (switch)
    (binary)
    (unary)
    (pipe)
] @range)
