([
  (at_rule)
  (call_expression)
  (charset_statement)
  (comment)
  (declaration)
  (extend_statement)
  (for_statement)
  (function_statement)
  (import_statement)
  (include_statement)
  (keyframes_statement)
  (media_statement)
  (mixin_statement)
  (placeholder)
  (rule_set)
  (single_line_comment)
] @range)

(arguments (_) @range)
(at_rule (_) @range)
(block (_) @range)
(call_expression (_) @range)
(charset_statement (_) @range)
(declaration (_) @range)
(extend_statement (_) @range)
(for_statement (_) @range)
(function_statement (_) @range)
(import_statement (_) @range)
(include_statement (_) @range)
(keyframe_block (_) @range)
(keyframes_statement (_) @range)
(media_statement (_) @range)
(mixin_statement (_) @range)
(parameters (_) @range)
(placeholder (_) @range)
(rule_set (_) @range)
(selectors (_) @range)
